### ISSUE TITLE
A fatal error occurred: Corrupt data, expected 0x1000 bytes but received 0xfe9 bytes  (ESPTOOL-651)

### ISSUE THREAD

**Issue by 1158linzy** [espressif/esptool#862] opened 2023-03-20 01:47 UTC
### Is your feature request related to a problem?

为什么，ESP8266读取Flash时会出现读取数据不完整问题。我尝试降低波特率，还是会出现这个问题

**Comment by dobairoland** [comment] 2023-03-20 07:45
Please use the forums at https://esp32.com/ for discussion and finding similar issues. Only open here issues if you are sure that the issue is with esptool and not a hardware design problem. Also, use the bug report template instead of the feature request - we need much more information in order to track down and solve issues.

Since there were four different issues opened at the same time, I suspect that maybe these were spams and closing all of them. I'm sorry if you a are a real person. Please follow my above recommendation.

**Closed by dobairoland** 2023-03-20 07:45 UTC
Labels: Type: Feature Request
