### ISSUE TITLE
ESPTOOL MS RDP upload to ESP32

### ISSUE THREAD

**Issue by unmateria** [espressif/esptool#565] opened 2020-10-04 13:47 UTC
Hi,

ESPTool fails (for me at least) for upload via Microsoft RDP port sharing. The only way I found to make it work is to force --trace on esptool. Then it works.

Error is serial.serialutil.SerialException: GetOverlappedResult failed (OSError(22, 'Reached the end of the file.', None, 38))

Would be great a version that works without having to use --trace, since it make upload really slow.

**Comment by projectgus** [comment] 2020-10-08 02:52
Hi @unmateria,

Thanks for the tip that `--trace` somehow fixes this problem, I'm guessing by slowing down the serial operations. This suggests that possibly we can retry when we see this error, and the next attempt will succeed.

I'm going to close this as a duplicate of #530, I see you also found that issue and commented on it.

**Closed by projectgus** 2020-10-08 02:52 UTC
Labels: enhancement
