### ISSUE TITLE
ESP-PROG: Connection fails ~50% of the time when using ESP-PROG & esp32s3 (ESPTOOL-826)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esptool#964] opened 2024-03-12 08:10 UTC
### Operating System

macOS 13.6.3

### Esptool Version

v4.6.2

### Python Version

3.9.6

### Chip Description

esp32s3

### Device Description

custom pcb

### Hardware Configuration

EN, RST, 3.3.v, GND, TX, RX are connected using the 6 wire harness found on the ESP-PROG to my custom PCB

### How is Esptool Run

command line

### Full Esptool Command Line that Was Run

/firmware/.espressif/python_env/idf5.1_py3.9_env/bin/python /firmware/esp-idf/components/esptool_py/esptool/esptool.py --port /dev/cu.usbserial-101 --chip esp32s3 --no-stub --after hard_reset get_security_info

### Esptool Output

```shell
esptool.py v4.6.2
Serial port /dev/cu.usbserial-101
Connecting......................................

A fatal error occurred: Failed to connect to ESP32-S3: No serial data received.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
```

### More Information

* If I manually put the device in to DOWNLOAD MODE (by holding Boot then pressing RST), it connects. 
* Also, even though connection fails, the device *does* reboot. So some communication is happening.
* when if succeeds, sometimes it connects quickly, othertimes it nearly hits the timeout but eventually works
* it only seems to connect 50% of the time.

Maybe we need a larger connection timeout?

### I Have Read the Troubleshooting Guide

- [X] I confirm I have read the troubleshooting guide.

**Comment by radimkarnis** [comment] 2024-03-12 12:46
Hello @chipweinberger,

honestly, this doesn't seem to be caused by the USB-to-UART bridge (CP2102N vs. FTDI). The FTDI drivers have been super solid over the years. 

> Also, even though connection fails, the device does reboot. So some communication is happening.

This is not "communication" - this happens even if the serial lines (`TX`, `RX`) are dead. The chip is being physically reset with the `EN`, `RTS` lines.

This seems more like a HW issue - either a bad connection (cold contact might be causing data loss) or insufficient power supply (there is a 3V3 / 5V jumper on the ESP-PROG - is it set correctly? Does your custom board have 5V regulator? Can you power it with 5V?

Also, isn't something bridging the EN pin to the ground? Maybe the chip is being held in reset. It would be great if you could verify the connections with a logic analyzer or an oscilloscope.

> Does espressif make an ESP-PROG with a CP2012N chip? 

We don't. But you can use any devkit with CP2012N as a makeshift ESP-PROG. Just disable the on-board ESP and use the devkits TX, RX, IO0, EN, GND, and 3V3 pins.

**Comment by chipweinberger** [comment] 2024-03-12 20:28
Thanks for the very very useful advice. I've copied my schematic below.

* I do have a 5V input with a regulator. 
* I'm forgot to add a power-on-reset circuit to my board. I'm not sure if it is necessary in this context.

**I wired it like so (devkit -> custom pcb):**
* tx -> tx
* rx -> rx
* 0 -> 0
* RST -> RST
* GND -> GND
* 3.3v -> 3.3v

When wiring it like this, the device does not turn on.  I'm not sure why.

**Then I tried changing to this:**
* 3.3.v -> RST

Now the device turns on, but of course it cannot be reset by the dev kit.

**I think ultimately, I want to wire it like this, right?**
* tx -> tx
* rx -> rx
* 0 -> 0
* RST -> RST
* GND -> GND
* 3.3v -> 3.3v (should skip this?)
* 5v -> 5v

**Schematic:**
<img width="962" alt="Screenshot 2024-03-12 at 1 19 40 PM" src="https://github.com/espressif/esptool/assets/1863934/f6a5faac-950f-4e80-ae95-69659fed76cc">

**Comment by chipweinberger** [comment] 2024-03-12 20:44
Ah, I think I found the RST issue. When I removed the esp32s3 from the DevKitC, I cut through the RST pad.

Looking at the PCB layout, RST goes *through* the pad. I need to be more careful modifying my DevKitC.

<img width="347" alt="Screenshot 2024-03-12 at 1 44 34 PM" src="https://github.com/espressif/esptool/assets/1863934/fd670129-108c-4d0b-96c5-d39483076f83">

**Comment by radimkarnis** [comment] 2024-03-14 14:03
> 3.3v -> 3.3v (should skip this?)
5v -> 5v

No, definitely do not power your ESP with both 3V3 and 5V, you risk burning it.

Sorry, but I can't help you more with your HW issues. If your board is a custom design, consider using our [free-of-charge schematic and PCB review service](https://www.espressif.com/en/contact-us/circuit-schematic-pcb-design-review).

Will close this as it's not an esptool issue, but a HW one.

**Closed as completed by radimkarnis** 2024-03-14 14:03 UTC
Labels: Type: Bug
