### ISSUE TITLE
esptool error

### ISSUE THREAD

**Issue by snahmad** [espressif/esptool#378] opened 2018-11-20 19:51 UTC
(Please delete any lines which don't apply.)

* Operating system: Windows 7
* Python version: 2.7.14
* ESP hardware in use: WROVER

File "C:/Work/library/esp32/master/esp-idf/components/esptool_py/esptool/esptool.py", line 2865, in <module>
    _main()
  File "C:/Work/library/esp32/master/esp-idf/components/esptool_py/esptool/esptool.py", line 2858, in _main
    main()
  File "C:/Work/library/esp32/master/esp-idf/components/esptool_py/esptool/esptool.py", line 2631, in main
    operation_func(args)
  File "C:/Work/library/esp32/master/esp-idf/components/esptool_py/esptool/esptool.py", line 2195, in elf2image
    image.save(args.output)
  File "C:/Work/library/esp32/master/esp-idf/components/esptool_py/esptool/esptool.py", line 1566, in save
    self.write_common_header(f, self.segments)
  File "C:/Work/library/esp32/master/esp-idf/components/esptool_py/esptool/esptool.py", line 1338, in write_common_header

**Comment by projectgus** [comment] 2018-11-25 23:44
Hi @snahmad,

I think this is the forum issue you posted here:
https://esp32.com/viewtopic.php?f=13&t=8119

and the same root cause as here:
https://github.com/espressif/esp-idf/issues/2727

The root cause is not in esptool (and seems to be fixed), although the bad error message is coming from esptool (fixed in 8a288e27c71868e9f18979ad428a954df582838d).

**Closed by projectgus** 2018-11-25 23:44 UTC
