### ISSUE TITLE
Failed Windows installation

### ISSUE THREAD

**Issue by bertiebeez** [espressif/esptool#574] opened 2020-11-08 19:35 UTC
* Operating system: 
Windows 8.1
* Python version: (`python -V` to check this) 
3.8

# Full esptool.py command line as run:
 c:\program tools\python38>pip install esptool

Example: esptool.py version

# Full output from esptool.py

(please copy and paste all lines of output)

c:\program files\pyton38>python.py
'esptools' not recognized as an internal or external command,
operable program or batch

# What is the expected behaviour?

Example: Print the version number

# Do you have any other information from investigating this?

Example: I tried on my friend's Windows 10 PC and the command works there

# Is there any other information you can think of which will help us reproduce this problem?

Example: Only crashes on first day of the month

**Comment by projectgus** [comment] 2020-11-09 06:56
Hi @bertiebeez ,

I'm sorry, there isn't enough information in this report to give you any help. Can you please give some more information, for example *exactly* what command you executed?

> c:\program files\pyton38>python.py
> 'esptools' not recognized as an internal or external command,

The command is `esptool.py`, not `esptools.py` - so maybe this is the root cause of the problem?

**Comment by bertiebeez** [comment] 2020-11-11 13:28
I was finally able to get it all sorted out. I was following a video from Dr zzs. He did not mention that you needed to run the cmd administrator. Once I did that, it installed just fine and worked as it should. Thank you for your responce!DavidSent from my Samsung Galaxy Tab®|PRO

-------- Original message --------

**Comment by projectgus** [comment] 2020-11-12 23:29
Thanks @bertiebeez for the update. In that case I'll close this issue.

**Closed by projectgus** 2020-11-12 23:29 UTC
Labels: bug
